#!bin/bash
Applications Documents Dropbox Downloads Web browser xbox game bar images Free course app
OfficeMobile Templates NetHood Saved games Printhood Recent Vagrant file test viseos clonedfiles
why?
