#!/usr/bin/env bash
#Displays 'Best School'. DIsplays Hi on the 9th iteration

index=0

while [$index -It 10]
do
  if [$index -eq 9]
  then
     echo "Hi"
   fi
   echo "Best School"
  ((index++))
done
